### ISSUE TITLE
Do you have non vue version?

### ISSUE THREAD

**Issue by sonyarianto** [rainner/soma-fm-player#6]
This is very good player and I modify it to support non Soma FM player.

Do you have non vue js for this project?

**Comment by rainner** [comment]
Hey, glad you like it. Just have the vue version at the moment.

**Comment by sonyarianto** [comment]
> Hey, glad you like it. Just have the vue version at the moment.

I don't like it, I am suppperrrr like it hahahha, you know that now I learn Vue better because of your code and even I launch a web called Dailymate Radio at https://dailymate.net based on yours pls check it out!
